### ISSUE TITLE
Why is this required?

### ISSUE THREAD

**Issue by binarymist** [formio/node-fetch-http-proxy#1]
Any special reason why proxy support wasn't just added to node-fetch? Surely it's a given that any self respecting http lib should support proxying?

**Comment by travist** [comment]
I honestly wish it weren't required, but i believe that node-fetch aims to be a pure representation of the fetch standard and that does not include requests through proxies. This library is here to solve the case of libraries that depend on the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables, from the deprecated request.js library. As soon as that library introduces that as a feature, this library will be deprecated, but my guess is that won't happen.
